<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <AssemblyName>BFS.ForzaLive</AssemblyName>
    <Nullable>disable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <GameDir Condition="'$(GameDir)' == ''">$(BFS_GAME_DIR)</GameDir>
  </PropertyGroup>
  <ItemGroup>
    <Reference Include="$(GameDir)/BepInEx/core/BepInEx.Core.dll" Private="false" />
    <Reference Include="$(GameDir)/BepInEx/core/BepInEx.Unity.IL2CPP.dll" Private="false" />
    <Reference Include="$(GameDir)/BepInEx/core/Il2CppInterop.Runtime.dll" Private="false" />
    <Reference Include="$(GameDir)/BepInEx/interop/*.dll" Private="false" />
  </ItemGroup>
</Project>
